# Generated by Django 2.0.3 on 2018-04-10 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webusers', '__first__'),
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webusers.WebUser'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('3', 'High'), ('2', 'Medium'), ('1', 'Low')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('N', 'Not started'), ('I', 'In progress'), ('C', 'Completed'), ('D', 'Done')], default='N', max_length=1),
        ),
    ]
