# Generated by Django 2.0.3 on 2018-04-23 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webusers', '0001_initial'),
        ('todos', '0002_auto_20180410_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='todos_todo_created', to='webusers.WebUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos_todo_assigned', to='webusers.WebUser'),
        ),
    ]
