# Generated by Django 2.0.3 on 2018-04-23 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_room'),
        ('todos', '0003_auto_20180423_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='house.Room'),
            preserve_default=False,
        ),
    ]
